### ISSUE TITLE
An error occurs in [octree_conv:61].

### ISSUE THREAD

**Issue by TrepangCat** [microsoft/O-CNN#135]
When `ocnn.OctreeDeConvBnRelu(depth=1, channel_in=3, channel_out=512, kernel_size=[3], stride=2)` is running, an error occurs in [octree_conv:61].
I think the `octree_conv` is `pytorch/cpp/octree_conv.cpp`. But I don't know why.

**Comment by TrepangCat** [comment]
And I try `test_all.py`. Here is the result:
```
test_backward (test_octree2col.Octree2ColTest) ... ok
test_forward (test_octree2col.Octree2ColTest) ... ok
test_forwardP1 (test_octree2col.Octree2ColTest) ... ok
test_octree2colP (test_octree2col.Octree2ColTest) ... ok
test_forward_backward1 (test_octree_align.OctreeAlignTest) ... ok
test_forward_backward2 (test_octree_align.OctreeAlignTest) ... ok
test_forward_backward3 (test_octree_align.OctreeAlignTest) ... ok
test_forward_and_backward (test_octree_conv.OctreeConvTest) ... ERROR
test_forward_and_backward (test_octree_deconv.OctreeDeconvTest) ... ERROR
test_decode_encode_key (test_octree_key.OctreeKeyTest) ... ERROR
test_search_key (test_octree_key.OctreeKeyTest) ... ERROR
test_xyz_key (test_octree_key.OctreeKeyTest) ... ERROR
test_xyz_key_64 (test_octree_key.OctreeKeyTest) ... ERROR
test_forward_and_backward_avg_pool (test_octree_pool.OctreePoolTest) ... ERROR
test_forward_and_backward_max_pool (test_octree_pool.OctreePoolTest) ... ERROR
test_forward_and_backward_max_unpool (test_octree_pool.OctreePoolTest) ... ERROR
test_octree_property (test_octree_property.OctreePropertyTest) ... ERROR
test_forward1 (test_octree_trilinear.OctreeTrilinearTest) ... ERROR
test_points_property (test_points_property.PointsPropertyTest) ... ok

======================================================================
ERROR: test_forward_and_backward (test_octree_conv.OctreeConvTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/media/brl/dataDisk/WangRuowei/3d_2021/O-CNN/pytorch/test/test_octree_conv.py", line 91, in test_forward_and_backward
    self.forward_and_backward(kernel_size[j], stride[i])
  File "/media/brl/dataDisk/WangRuowei/3d_2021/O-CNN/pytorch/test/test_octree_conv.py", line 61, in forward_and_backward
    out3.backward(pesudo_grad2)
  File "/home/brl/anaconda3/envs/pt190/lib/python3.9/site-packages/torch/_tensor.py", line 255, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "/home/brl/anaconda3/envs/pt190/lib/python3.9/site-packages/torch/autograd/__init__.py", line 147, in backward
    Variable._execution_engine.run_backward(
RuntimeError: merge_sort: failed to synchronize: cudaErrorIllegalAddress: an illegal memory access was encountered

======================================================================
ERROR: test_forward_and_backward (test_octree_deconv.OctreeDeconvTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/media/brl/dataDisk/WangRuowei/3d_2021/O-CNN/pytorch/test/test_octree_deconv.py", line 91, in test_forward_and_backward
    self.forward_and_backward(kernel_size[j], stride[i])
  File "/media/brl/dataDisk/WangRuowei/3d_2021/O-CNN/pytorch/test/test_octree_deconv.py", line 31, in forward_and_backward
    octree = octree.cuda()
RuntimeError: CUDA error: an illegal memory access was encountered

======================================================================
ERROR: test_decode_encode_key (test_octree_key.OctreeKeyTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/media/brl/dataDisk/WangRuowei/3d_2021/O-CNN/pytorch/test/test_octree_key.py", line 10, in test_decode_encode_key
    octree = ocnn.octree_batch(samples).cuda()
RuntimeError: CUDA error: an illegal memory access was encountered

======================================================================
ERROR: test_search_key (test_octree_key.OctreeKeyTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/media/brl/dataDisk/WangRuowei/3d_2021/O-CNN/pytorch/test/test_octree_key.py", line 33, in test_search_key
    octree = ocnn.octree_batch(samples).cuda()
RuntimeError: CUDA error: an illegal memory access was encountered

======================================================================
ERROR: test_xyz_key (test_octree_key.OctreeKeyTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/media/brl/dataDisk/WangRuowei/3d_2021/O-CNN/pytorch/test/test_octree_key.py", line 25, in test_xyz_key
    octree = ocnn.octree_batch(samples).cuda()
RuntimeError: CUDA error: an illegal memory access was encountered

======================================================================
ERROR: test_xyz_key_64 (test_octree_key.OctreeKeyTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/media/brl/dataDisk/WangRuowei/3d_2021/O-CNN/pytorch/test/test_octree_key.py", line 47, in test_xyz_key_64
    xyz = torch.cuda.ShortTensor([[2049, 4095, 8011, 1], [511, 4095, 8011, 0]])
RuntimeError: CUDA error: an illegal memory access was encountered

======================================================================
ERROR: test_forward_and_backward_avg_pool (test_octree_pool.OctreePoolTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/media/brl/dataDisk/WangRuowei/3d_2021/O-CNN/pytorch/test/test_octree_pool.py", line 91, in test_forward_and_backward_avg_pool
    octree = octree.to('cuda')
RuntimeError: CUDA error: an illegal memory access was encountered

======================================================================
ERROR: test_forward_and_backward_max_pool (test_octree_pool.OctreePoolTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/media/brl/dataDisk/WangRuowei/3d_2021/O-CNN/pytorch/test/test_octree_pool.py", line 28, in test_forward_and_backward_max_pool
    octree = octree.to('cuda')
RuntimeError: CUDA error: an illegal memory access was encountered

======================================================================
ERROR: test_forward_and_backward_max_unpool (test_octree_pool.OctreePoolTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/media/brl/dataDisk/WangRuowei/3d_2021/O-CNN/pytorch/test/test_octree_pool.py", line 59, in test_forward_and_backward_max_unpool
    octree = octree.to('cuda')
RuntimeError: CUDA error: an illegal memory access was encountered

======================================================================
ERROR: test_octree_property (test_octree_property.OctreePropertyTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/media/brl/dataDisk/WangRuowei/3d_2021/O-CNN/pytorch/test/test_octree_property.py", line 60, in test_octree_property
    self.octree_property(on_cuda=True)
  File "/media/brl/dataDisk/WangRuowei/3d_2021/O-CNN/pytorch/test/test_octree_property.py", line 13, in octree_property
    octree = octree.cuda()
RuntimeError: CUDA error: an illegal memory access was encountered

======================================================================
ERROR: test_forward1 (test_octree_trilinear.OctreeTrilinearTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/media/brl/dataDisk/WangRuowei/3d_2021/O-CNN/pytorch/test/test_octree_trilinear.py", line 11, in test_forward1
    octree = ocnn.octree_batch(ocnn.octree_samples(['octree_1', 'octree_1'])).cuda()
RuntimeError: CUDA error: an illegal memory access was encountered

----------------------------------------------------------------------
Ran 19 tests in 3.231s

FAILED (errors=11)

```

**Comment by TrepangCat** [comment]
I run the `test_***.py` in `pytorch/test`, and find that three of them are not OK.
First, `test_octree2col.py`
```
Ran 4 tests in 1.863s

OK

Process finished with exit code 0
/home/brl/anaconda3/envs/pt190_py37/lib/python3.7/site-packages/torch/autograd/gradcheck.py:633: UserWarning: Input #0 requires gradient and is not a double precision floating point or complex. This check will likely fail if all the inputs are not of double precision floating point or complex. 
  f'Input #{idx} requires gradient and '
```
Second, `test_octree_deconv.py`
```
Failure
Traceback (most recent call last):
  File "/media/brl/dataDisk/WangRuowei/3d_2021/O-CNN/pytorch/test/test_octree_deconv.py", line 91, in test_forward_and_backward
    self.forward_and_backward(kernel_size[j], stride[i])
  File "/media/brl/dataDisk/WangRuowei/3d_2021/O-CNN/pytorch/test/test_octree_deconv.py", line 77, in forward_and_backward
    atol=1e-06))
AssertionError: False is not true





Ran 1 test in 1.859s

FAILED (failures=1)
```
Third, `test_octree_trilinear.py`
```
Ran 1 test in 1.483s

FAILED (errors=1)

Error
Traceback (most recent call last):
  File "/media/brl/dataDisk/WangRuowei/3d_2021/O-CNN/pytorch/test/test_octree_trilinear.py", line 13, in test_forward1
    linear = ocnn.octree_trilinear(data, octree, depth, depth + 1)
  File "/home/brl/anaconda3/envs/pt190_py37/lib/python3.7/site-packages/ocnn-1.0-py3.7-linux-x86_64.egg/ocnn/modules.py", line 286, in octree_trilinear
    output = octree_trilinear_pts(data, octree, depth, xyz)
  File "/home/brl/anaconda3/envs/pt190_py37/lib/python3.7/site-packages/ocnn-1.0-py3.7-linux-x86_64.egg/ocnn/modules.py", line 271, in octree_trilinear_pts
    output = torch.sparse.mm(mat, data)
  File "/home/brl/anaconda3/envs/pt190_py37/lib/python3.7/site-packages/torch/sparse/__init__.py", line 91, in mm
    return torch._sparse_mm(mat1, mat2)
RuntimeError: merge_sort: failed to synchronize: cudaErrorIllegalAddress: an illegal memory access was encountered
```

**Comment by TrepangCat** [comment]
Finally, I find out the result. 
When using `OctreeDeconv()` with stride=2 at depth `d`, we should use `octree_grow()` at depth `d` and `d+1`

**Comment by TrepangCat** [comment]
Finally, I find out the reason. 
When using `OctreeDeconv()` with stride=2 at depth `d`, we should use `octree_grow()` at depth `d` and `d+1`
