### ISSUE TITLE
RuntimeError: merge_sort: failed to synchronize: cudaErrorIllegalAddress: an illegal memory access was encountered

### ISSUE THREAD

**Issue by TrepangCat** [microsoft/O-CNN#136]
When I run `pytorch/testtest_octree_trilinear.py`, the error occurs:
```
Ran 1 test in 1.483s

FAILED (errors=1)

Error
Traceback (most recent call last):
  File "/media/brl/dataDisk/WangRuowei/3d_2021/O-CNN/pytorch/test/test_octree_trilinear.py", line 13, in test_forward1
    linear = ocnn.octree_trilinear(data, octree, depth, depth + 1)
  File "/home/brl/anaconda3/envs/pt190_py37/lib/python3.7/site-packages/ocnn-1.0-py3.7-linux-x86_64.egg/ocnn/modules.py", line 286, in octree_trilinear
    output = octree_trilinear_pts(data, octree, depth, xyz)
  File "/home/brl/anaconda3/envs/pt190_py37/lib/python3.7/site-packages/ocnn-1.0-py3.7-linux-x86_64.egg/ocnn/modules.py", line 271, in octree_trilinear_pts
    output = torch.sparse.mm(mat, data)
  File "/home/brl/anaconda3/envs/pt190_py37/lib/python3.7/site-packages/torch/sparse/__init__.py", line 91, in mm
    return torch._sparse_mm(mat1, mat2)
RuntimeError: merge_sort: failed to synchronize: cudaErrorIllegalAddress: an illegal memory access was encountered
```

**Comment by wang-ps** [comment]
The code has been tested before release. 
What's your PyTorch version and Cuda version? It seems that the error is caused by the sparse matrix product of PyTorch.

**Comment by TrepangCat** [comment]
pytorch 1.9.0
cuda 11.1
GPU RTX 3080

**Comment by wang-ps** [comment]
I have not thoroughly tested the code with pytorch 1.9.0. Please follow the instructions in our readme file and try the code with pytorch-1.7.0.

**Comment by TrepangCat** [comment]
Thanks, I will try it.
