### ISSUE TITLE
InvalidArgumentError: No OpKernel was registered to support Op 'OctreeToCol'

### ISSUE THREAD

**Issue by aradhyamathur** [microsoft/O-CNN#88]
Upon running the test_octree2col.py I encountered the following error, would like to get some guidance pertaining to it. 

```
tensorflow.python.framework.errors_impl.InvalidArgumentError: No OpKernel was registered to support Op 'OctreeToCol' used by {{node OctreeToCol}}with these attrs: [stride=1, depth=1, kernel_size=[3, 3, 3]]
Registered devices: [CPU, XLA_CPU]
Registered kernels:
  device='GPU'

	 [[OctreeToCol]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test_octree2col.py", line 67, in test_forward
    out_nn = data_out.eval()
  File "/home/thor/anaconda3/envs/tf-1.14.0/lib/python3.7/site-packages/tensorflow/python/framework/ops.py", line 731, in eval
    return _eval_using_default_session(self, feed_dict, self.graph, session)
  File "/home/thor/anaconda3/envs/tf-1.14.0/lib/python3.7/site-packages/tensorflow/python/framework/ops.py", line 5579, in _eval_using_default_session
    return session.run(tensors, feed_dict)
  File "/home/thor/anaconda3/envs/tf-1.14.0/lib/python3.7/site-packages/tensorflow/python/framework/test_util.py", line 1493, in run
    return super(ErrorLoggingSession, self).run(*args, **kwargs)
  File "/home/thor/anaconda3/envs/tf-1.14.0/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 950, in run
    run_metadata_ptr)
  File "/home/thor/anaconda3/envs/tf-1.14.0/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1173, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/thor/anaconda3/envs/tf-1.14.0/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1350, in _do_run
    run_metadata)
  File "/home/thor/anaconda3/envs/tf-1.14.0/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1370, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: No OpKernel was registered to support Op 'OctreeToCol' used by node OctreeToCol (defined at <string>:87) with these attrs: [stride=1, depth=1, kernel_size=[3, 3, 3]]
Registered devices: [CPU, XLA_CPU]
Registered kernels:
  device='GPU'

	 [[OctreeToCol]]

Errors may have originated from an input operation.
Input Source operations connected to node OctreeToCol:
 OctreeBatch (defined at <string>:468)

```

**Comment by wang-ps** [comment]
I updated the code for unit tests, you can change the working directory to `tensorflow/test` and run the following command: 
```shell
python test_all.py
```
