### ISSUE TITLE
Invalid argument: Feature: octree (data type: string) is required but could not be found.

### ISSUE THREAD

**Issue by aradhyamathur** [microsoft/O-CNN#91]
Upon running the octree autoencoder I receive the following error, can you please guide as to what might be the underlying cause

```
W tensorflow/core/framework/op_kernel.cc:1502] OP_REQUIRES failed at example_parsing_ops.cc:240 : Invalid argument: Feature: octree (data type: string) is required but could not be found.
Traceback (most recent call last):
  File "/home/aradhya/anaconda3/envs/tf-1.14.0/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1356, in _do_call
    return fn(*args)
  File "/home/aradhya/anaconda3/envs/tf-1.14.0/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1341, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/home/aradhya/anaconda3/envs/tf-1.14.0/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1429, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InvalidArgumentError: 2 root error(s) found.
  (0) Invalid argument: Feature: octree (data type: string) is required but could not be found.
	 [[{{node ParseSingleExample/ParseSingleExample}}]]
	 [[dataset/IteratorGetNext]]
	 [[solver/step_lr/PiecewiseConstant/case/Assert/AssertGuard/Assert/data_0/_103]]
  (1) Invalid argument: Feature: octree (data type: string) is required but could not be found.
	 [[{{node ParseSingleExample/ParseSingleExample}}]]
	 [[dataset/IteratorGetNext]]
0 successful operations.
0 derived errors ignored.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "run_ae.py", line 99, in <module>
    solver.train()
  File "/home/aradhya/Surface Reconstruction/OCNN_Ojaswi/tensorflow/script/tfsolver.py", line 62, in train
    summary, _ = sess.run([self.summ_train, self.op_train])
  File "/home/aradhya/anaconda3/envs/tf-1.14.0/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 950, in run
    run_metadata_ptr)
  File "/home/aradhya/anaconda3/envs/tf-1.14.0/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1173, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/aradhya/anaconda3/envs/tf-1.14.0/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1350, in _do_run
    run_metadata)
  File "/home/aradhya/anaconda3/envs/tf-1.14.0/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1370, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: 2 root error(s) found.
  (0) Invalid argument: Feature: octree (data type: string) is required but could not be found.
	 [[{{node ParseSingleExample/ParseSingleExample}}]]
	 [[dataset/IteratorGetNext]]
	 [[solver/step_lr/PiecewiseConstant/case/Assert/AssertGuard/Assert/data_0/_103]]
  (1) Invalid argument: Feature: octree (data type: string) is required but could not be found.
	 [[{{node ParseSingleExample/ParseSingleExample}}]]
	 [[dataset/IteratorGetNext]]
0 successful operations.
0 derived errors ignored.

```

**Comment by wang-ps** [comment]
Please pull the latest code.

**Comment by wang-ps** [comment]
Please refer to the instructions in [Shape Autoencoder](https://github.com/microsoft/O-CNN/blob/master/docs/autoencoder.md) and [Shape completion](https://github.com/microsoft/O-CNN/blob/master/docs/completion.md) to train an Autoencoder with the Tensorflow
